# Workflow copied from https://simonwillison.net/2020/Jan/21/github-actions-cloud-run/
name: Fetch latest Irish COVID data

on: [workflow_dispatch] #repository_dispatch: #Can run it manually also
  #schedule:
   # - cron: '0 2 * * *' #Execute at  2am every day

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scheduled-fetch-data"
  scheduled-fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: checkoout the code
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: configure pip caching
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch, update and commit COVID-Ireland data
      run: . covid-ireland/pull-data.sh
    - name: Set up Cloud Run
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud components install beta
        gcloud config set run/region europe-west1
        gcloud config set project data-hosting-291810
        datasette publish cloudrun covid-ireland.db --service covid-ie
